import bcrypt from 'bcryptjs';

const data = {
  products: [
    {
      //_id: '1',
      name: 'Top con falda',
      slug: 'conjunto-negro-1',
      category: 'Conjunto',
      image: '/images/p1.PNG', // 679px × 829px
      price: 120,
      countInStock: 2,
      brand: 'moda&estilo',
      rating: 4.5,
      numReviews: 10,
      description:
        'Hermoso crop top negro manga larga y minifalda en cuerina negro',
    },
    {
      //_id: '2',
      name: 'Top con short',
      slug: 'conjunto-blanco-1',
      category: 'Conjunto',
      image: '/images/p2.PNG', // 679px
      price: 250,
      countInStock: 20,
      brand: 'moda&estilo',
      rating: 4.0,
      numReviews: 10,
      description: 'Sutil crop top blanco y short beige',
    },
    {
      //_id: '3',
      name: 'Set fucsia',
      slug: 'conjunto-fucsia',
      category: 'Conjunto',
      image: '/images/p3.PNG',
      price: 25,
      countInStock: 15,
      brand: 'moda&estilo',
      rating: 4.5,
      numReviews: 14,
      description: 'Top, falda y blazer en drill color fucsia',
    },
    {
      //_id: '4',
      name: 'Conjunto blanco',
      slug: 'conjunto-blanco-2',
      category: 'Conjunto',
      image: '/images/p4.PNG',
      price: 65,
      countInStock: 2,
      brand: 'moda&estilo',
      rating: 4.5,
      numReviews: 10,
      description: 'Top asimetrico color y pantalon clasico color blanco',
    },
    {
      //_id: '5',
      name: 'Crop top y short',
      slug: 'conjunto-blanco-3',
      category: 'Conjunto',
      image: '/images/p5.PNG',
      price: 65,
      countInStock: 2,
      brand: 'moda&estilo',
      rating: 4.5,
      numReviews: 10,
      description: 'Crop top color blanco y short en tela jean',
    },
    {
      //_id: '6',
      name: 'Crop top y falda',
      slug: 'conjunto-blanco-4',
      category: 'Conjunto',
      image: '/images/p6.PNG',
      price: 65,
      countInStock: 2,
      brand: 'moda&estilo',
      rating: 4.5,
      numReviews: 10,
      description: 'Hermosos crop top rosa y falda en color blanco',
    },
    {
      //_id: '7',
      name: 'Blusa y short',
      slug: 'conjunto-blanco-6',
      category: 'Conjunto',
      image: '/images/p7.PNG',
      price: 65,
      countInStock: 2,
      brand: 'moda&estilo',
      rating: 4.5,
      numReviews: 10,
      description: 'elegante blusa con botones marrones y un short blanco',
    },
    {
      //_id: '8',
      name: 'Crop top negro y falda',
      slug: 'conjunto-blanco-5',
      category: 'Conjunto',
      image: '/images/p8.PNG',
      price: 65,
      countInStock: 2,
      brand: 'moda&estilo',
      rating: 4.5,
      numReviews: 10,
      description: 'Hermosos crop top negro y una falda en tela jean',
    },
  ],
  users: [
    {
      name: 'Victor',
      email: 'admin@ejemplo.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Camila',
      email: 'user@ejemplo.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
};
export default data;
